### ISSUE TITLE
training from scratch

### ISSUE THREAD

**Issue by cvtower** [jinfagang/ssds_pytorch#2]
Hi @jinfagang ,

Nice work!
Could you reproduce valid performance without pre-trained model?
Seems like that the "old issue" -https://github.com/ShuangXieIrene/ssds.pytorch/issues/30
still exists.

**Comment by cvtower** [comment]
Sorry, i did not read the detail implement code since my main task is to verify my network arch based on mobilenet-ssd implement.
The cfg file for most models contain only 'test' phase rather than 'train', i think this might be the root-cause?

**Comment by lucasjinreal** [comment]
@cvtower  Hi, you can change config file to train or test

**Comment by cvtower** [comment]
Sorry, i did not read the detail implement code since my main task is to verify my network arch based on mobilenet-ssd implement.
The cfg file for most models contain only 'test' phase rather than 'train', i think this might be the root-cause.
Now i could train the model.

Thanks very much for your help!
